# Generated by Django 2.1 on 2018-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovaya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recount',
            name='total_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recount',
            name='user_portions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
