# Generated by Django 2.1 on 2018-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovaya', '0004_auto_20180825_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('gram', 'граммы'), ('teasp', 'чайные ложки'), ('tablsp', 'столовые ложки'), ('cup', 'чашки'), ('piece', 'штуки')], max_length=24, unique=True),
        ),
    ]
