# Generated by Django 2.1 on 2018-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovaya', '0006_auto_20180825_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('l', 'литры'), ('ml', 'милилитры'), ('kg', 'килограммы'), ('stalk', 'стебли'), ('pinch', 'щепотки'), ('knife', 'на кончике ножа'), ('denticle', 'зубчики'), ('sheaf', 'пучки'), ('chunk', 'куски'), ('jar', 'банки'), ('head', 'головки'), ('taste', 'по вкусу'), ('gram', 'граммы'), ('teasp', 'чайные ложки'), ('tablsp', 'столовые ложки'), ('cup', 'стаканы'), ('piece', 'штуки')], max_length=24, unique=True),
        ),
    ]
