# Generated by Django 2.1 on 2018-08-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=24)),
                ('action', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientdish',
            name='default_number_of_servings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('l', 'литры'), ('ml', 'милилитры'), ('kg', 'килограммы'), ('stalk', 'стебли'), ('pinch', 'щепотки'), ('knife', 'на кончике ножа'), ('denticle', 'зубчики'), ('sheaf', 'пучки'), ('chunk', 'куски'), ('jar', 'банки'), ('head', 'головки'), ('taste', 'по вкусу'), ('gram', 'граммы'), ('teasp', 'чайные ложки'), ('tablsp', 'столовые ложки'), ('cup', 'стаканы'), ('piece', 'штуки')], max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.Dish'),
        ),
    ]
