# Generated by Django 2.1 on 2018-09-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0002_auto_20180829_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientdish',
            old_name='default_number_of_servings',
            new_name='amount',
        ),
    ]
